Lab456/Models/Following.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Lab456.Models
{
    public class Following
    {
        [Key]
        [Column(Order = 1)]
        public string FollowerId { get; set; }


        [Key]
        [Column(Order = 2)]
        public string FolloweeId { get; set; }

        public ApplicationUser Follower { get; set; }
        public ApplicationUser Followee { get; set; }
    }
}

Lab456/ViewModels/CoursesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Lab456.Models;

namespace Lab456.ViewModels
{
    public class CoursesViewModel
    {
        public IEnumerable<Course> UpcomingCourses { get; set; }
        public bool ShowAction { get; set; }
    }
}

Lab456/Controllers/CoursesController.cs
using Lab456.Models;
using Lab456.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab456.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _dbConText;
        public CoursesController()
        {
            _dbConText = new ApplicationDbContext();
        }
        // GET: Courses
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbConText.Categories.ToList()
            };
            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbConText.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.Place
            };
            _dbConText.Courses.Add(course);
            _dbConText.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        public ActionResult Attending()
        {
            var userId = User.Identity.GetUserId();
            var courses = _dbConText.Attendances
                .Where(a => a.AttendeeId == userId)
                .Select(a => a.Course)
                .Include(l => l.Lecturer)
                .Include(l => l.Category)
                .ToList();
            var viewModel = new CoursesViewModel
            {
                UpcomingCourses = courses,
                ShowAction = User.Identity.IsAuthenticated
            };
            return View(viewModel);
        }

        [Authorize]
        public ActionResult Following()
        {
            var userId = User.Identity.GetUserId();
            var viewModel = _dbConText.Followings
                .Where(a => a.FollowerId == userId)
                .Select(a => a.Followee)
                .ToList();
            return View(viewModel);
        }

        [Authorize]
        public ActionResult Mine()
        {
            var userId = User.Identity.GetUserId();
            var courses = _dbConText.Courses
                .Where(c => c.LecturerId == userId && c.DateTime > DateTime.Now)
                .Include(l => l.Lecturer)
                .Include(c => c.Category)
                .ToList();
            return View(courses);
        }

        [Authorize]
        public ActionResult Edit(int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbConText.Courses.Single(c => c.Id == id && c.LecturerId == userId);
            var viewModel = new CourseViewModel
            {
                Categories = _dbConText.Categories.ToList(),
                Date = course.DateTime.ToString("dd/MM/yyyy"),
                Time = course.DateTime.ToString("HH:mm"),
                Category = course.CategoryId,
                Place = course.Place,
                Heading = "Edit Course",
                Id = course.Id
            };
            return View("Create", viewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Categories = _dbConText.Categories.ToList();
                return View("Create", viewModel);
            }
            var userId = User.Identity.GetUserId();
            var course = _dbConText.Courses.Single(c => c.Id == viewModel.Id && c.LecturerId == userId);

            course.Place = viewModel.Place;
            course.DateTime = viewModel.GetDateTime();
            course.CategoryId = viewModel.Category;

            _dbConText.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

Lab456/Controllers/FollowingsController.cs
using Lab456.DTOs;
using Lab456.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Lab456.Controllers
{
    public class FollowingsController : ApiController
    {
        private readonly ApplicationDbContext _dbContext;

        public FollowingsController()
        {
            _dbContext = new ApplicationDbContext();
        }

        [HttpPost]
        public IHttpActionResult Follow(FollowingDto followingDto)
        {
            var userId = User.Identity.GetUserId();
            if (_dbContext.Followings.Any(f => f.FollowerId == userId && f.FolloweeId == followingDto.FolloweeId))
                return BadRequest("Following aleary exist!");

            var following = new Following
            {
                FollowerId = userId,
                FolloweeId = followingDto.FolloweeId
            };

            _dbContext.Followings.Add(following);
            _dbContext.SaveChanges();

            return Ok();
        }
        [HttpDelete]
        public IHttpActionResult DeleteFollow(string Id)
        {
            var userId = User.Identity.GetUserId();
            var following = _dbContext.Followings.SingleOrDefault(f => f.FollowerId == userId && f.FolloweeId == Id);
            if (following == null)
            {
                return NotFound();
            }
            _dbContext.Followings.Remove(following);
            _dbContext.SaveChanges();
            return Ok(Id);
        }
    }
}

Lab456/Controllers/api/CoursesController.cs
using Lab456.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Lab456.Controllers.api
{
    public class CoursesController : ApiController
    {
        public ApplicationDbContext _dbContext { get; set; }

        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }

        [HttpDelete]
        public IHttpActionResult Cancel(int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);
            if (course.IsCanceled)
                return NotFound();
            course.IsCanceled = true;
            _dbContext.SaveChanges();
            return Ok();
        }
    }
}

Lab456/Views/Courses/Attending.cshtml
@model Lab456.ViewModels.CoursesViewModel
@using Microsoft.AspNet.Identity;
@using Lab456.Models;
@{
    ViewBag.Title = "Attending";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Attending</h2>
<ul class="course">
    @foreach (var course in Model.UpcomingCourses)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecturer">
                    @course.Lecturer.Name
                </span>
                <br />
                <span class="category">
                    @course.Category.Name
                </span>
                @if (Model.ShowAction)
                {
                    var User_ID = User.Identity.GetUserId();
                    ApplicationDbContext _dbContext = new ApplicationDbContext();
                    bool isGoing = _dbContext.Attendances.Any(a => a.CourseId == course.Id && a.AttendeeId == User_ID);

                    if (isGoing)
                    {
                        <button data-course-id="@course.Id" class="btn btn-info btn-sm js-toggle-attendance">Going</button>
                    }
                    else
                    {
                        <button data-course-id="@course.Id" class="btn btn-default btn-sm js-toggle-attendance">Going?</button>
                    }

                }
            </div>
        </li>
    }
</ul>

@section scripts
{
    <script>
        $(document).ready(function () {
            $(".js-toggle-attendance").click(function (e) {
                var button = $(e.target);
                if (button.hasClass("btn-default")) {
                    $.post("/api/Attendances", { courseId: button.attr("data-course-id") })
                        .done(function () {
                            button
                                .removeClass("btn-default")
                                .addClass("btn-info")
                                .text("Going");
                        })
                        .fail(function () {
                            alert("Something failed!");
                        });
                }
                else {
                    $.ajax({
                        url: "/api/attendances/" + button.attr("data-course-id"),
                        method: "DELETE"
                    })
                        .done(function () {
                            button
                                .removeClass("btn-info")
                                .addClass("btn-default")
                                .text("Going?");
                        })
                        .fail(function () {
                            alert("Something failed!");
                        });
                }

            });
            $(".js-toggle-follow").click(function (e) {
                var button = $(e.target);
                if (button.hasClass("btn-default")) {
                    $.post("/api/followings", { followeeId: button.attr("data-user-id") })
                        .done(function () {
                            button
                                .removeClass("btn-default")
                                .text("Following");
                        })
                        .fail(function () {
                            alert("Something failed!");
                        });
                }
                else {
                    $.ajax({
                        url: "/api/followings/" + button.attr("data-user-id"),
                        method: "DELETE"
                    })
                        .done(function () {
                            button
                                .addClass("btn-default")
                                .text("Follow");
                        })
                        .fail(function () {
                            alert("Something failed! (2)");
                        });
                }
            });
        });

    </script>
}

Lab456/Views/Courses/Create.cshtml
@model Lab456.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>
@using (Html.BeginForm("Create", "Courses"))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Place)
        @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
        @Html.ValidationMessageFor(m=>m.Place)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Date)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Time)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Category)
        @Html.DropDownListFor(m => m.Category,
             new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Category)
    </div>
    <button type="submit" value="Save" class="btn btn-primary">Save</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jquerycal");
    }

Lab456/Views/Courses/Following.cshtml
@model IEnumerable<Lab456.Models.ApplicationUser>
@{
    ViewBag.Title = "Following";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Following</h2>
<ul>

    @foreach (var viewModel in @Model)
    {
        <li>
            <span style="font-weight:bold">@viewModel.Name</span>
            <button class="btn btn-info btn-sm js-toggle-follow" data-user-id="@viewModel.Id">
                Following
            </button>
            <br />
            <br />
        </li>

    }
</ul>

@section scripts
{
    <script>
        $(document).ready(function () {
            $(".js-toggle-follow").click(function (e) {
                var button = $(e.target);
                if (button.hasClass("btn-default")) {
                    $.post("/api/followings", { followeeId: button.attr("data-user-id") })
                        .done(function () {
                            button
                                .removeClass("btn-default")
                                .addClass("btn-info")
                                .text("Following");
                        })
                        .fail(function () {
                            alert("Something failed!");
                        });
                }
                else {
                    $.ajax({
                        url: "/api/followings/" + button.attr("data-user-id"),
                        method: "DELETE"
                    })
                        .done(function () {
                            button
                                .removeClass("btn-info")
                                .addClass("btn-default")
                                .text("Follow");
                        })
                        .fail(function () {
                            alert("Something failed! (2)");
                        });
                }
            });
        });
    </script>
}

Lab456/Views/Courses/Mine.cshtml
@model IEnumerable<Lab456.Models.Course>
@{
    ViewBag.Title = "Mine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mine</h2>
<ul class="course">
    @foreach (var course in Model)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecturer">
                    @course.Lecturer.Name
                </span><br />
                <span class="category">
                    @course.Category.Name
                </span>
            </div>
            <div class="action">
                <a href="@Url.Action("Edit","Courses", new { id = course.Id })">Edit</a> ||
                <a href="#" class="js-cancel-course" data-course-id="@course.Id">Cancel</a>
            </div>
        </li>
    }
</ul>

@section scripts
{
    <script>
        $(document).ready(function () {
            $(".js-cancel-course").click(function (e) {
                e.preventDefault();
                var link = $(e.target);
                bootbox.confirm("Are you sure to cancel?",
                    function () {
                        $.ajax({
                            url: "/api/courses/" + link.attr("data-course-id"),
                            method: "DELETE"
                        })
                            .done(function () {
                                link.parents("li").fadeOut(function () {
                                    $(this).remove();
                                });
                            })
                            .fail(function () {
                                alert("Something failed!");
                            });
                    });
            });
        });
    </script>
}